TargetRubyVersion: 3.0

AllCops:
  Severity: { default: warning }

Exclude:
  - vendor/**/* # Exclude the vendor directory
  - db/**/*     # Exclude the db directory

Metrics/BlockLength:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: false

Layout/LineLength:
  Max: 120
Style/FrozenStringLiteralComment:
  Enabled: true
